### ISSUE TITLE
app is undefined in renderer process.

### ISSUE THREAD

**Issue by bloodbee** [michalzaq12/electron-nuxt#602]
### How to reproduce 

Just create any component or page in your electron-nuxt project.

in your script tags : 
`const { app } = require('electron')` OR `import { app } from 'electron'`

in your mounted() method for example : 
```
console.log(app.getPath('appData'))
console.log(app.getPath('pictures'))
console.log(app.getPath('userData'))
```

Error : 
`TypeError: Cannot read property 'getPath' of undefined`

As said in documentation (https://michalzaq12.github.io/electron-nuxt/guide/#static-resources), resources is where to store read-only datas, such as external files, etc... But when we need write access we should use app.getPath('appData').
So this is what I want to use to store my users files such as images, videos, etc...

Or maybe i'm doing it wrong, so what is the best way to handle user's files storing ?

**Comment by michalzaq12** [comment]
Fixed in 1.7.0

**Comment by gl13c** [comment]
This issue persists in the latest version with the same reproduction steps.

**Comment by ricvillagrana** [comment]
This still persists, I suggest reopening this issue.
